package at.xidev.bikechallenge.app;

// Generated Apr 6, 2014 5:45:52 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;
	private Integer score;

	public User() {
	}

	public User(String name) {
		this.name = name;
	}

	public User(String name, String password, Integer score) {
		this.name = name;
		this.password = password;
		this.score = score;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

}
