package at.xidev.bikechallenge.model;

// Generated 23.04.2014 16:22:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private Integer id;
	private float distance;
	private Date starttime;
	private Date stoptime;
	private String userId;

	public Route() {
	}

	public Route(float distance, Date starttime, Date stoptime, String userId) {
		this.distance = distance;
		this.starttime = starttime;
		this.stoptime = stoptime;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public float getDistance() {
		return this.distance;
	}

	public void setDistance(float distance) {
		this.distance = distance;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getStoptime() {
		return this.stoptime;
	}

	public void setStoptime(Date stoptime) {
		this.stoptime = stoptime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
