package at.xidev.bikechallenge.model;// Generated 23.04.2014 16:22:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

    private Integer id;
    private float distance;
    private Date startTime;
    private Date stopTime;
    private int userId;

    public Route() {
    }

    public Route(float distance, Date startTime, Date stopTime, int userId) {
        this.distance = distance;
        this.startTime = startTime;
        this.stopTime = stopTime;
        this.userId = userId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public float getDistance() {
        return this.distance;
    }

    public void setDistance(float distance) {
        this.distance = distance;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getStopTime() {
        return this.stopTime;
    }

    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

}
